fc=gfortran


all: cacuns norm rdsac stksac


cacuns : cacuns.f90
	$(fc) -o cacuns cacuns.f90
norm : norm.f90
	$(fc) -o norm norm.f90
rdsac : rdsac.f90
	$(fc) -o rdsac rdsac.f90
stksac : stksac.f90
	$(fc) -o stksac stksac.f90
